[package]
name = "tty-todo"
version = "0.1.0"
authors = ["Raadwan Masum <piraadwan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
